language: python
dist: Xenial
python: "3.7"

install:
 - var1="$(pwd)"

 - git clone https://github.com/m-labs/migen
 - cd migen
 - python3 setup.py develop
 - cd $var1

 - git clone https://github.com/enjoy-digital/litex
 - cd litex
 - python3 setup.py develop
 - cd $var1
    
jobs:
  include:
   - script: python -m unittest test.__init__.py
   - script: python -m unittest test.common.py
   - script: python -m unittest test.test_axi.py
   - script: python -m unittest test.test_bist.py
   - script: python -m unittest test.test_downconverter.py
   - script: python -m unittest test.test_ecc.py
   - script: python -m unittest test.test_examples.py
   - script: python -m unittest test.test_upconverter.py
